/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_desacocarrybeauty_gpu_image_GPUImageNativeLibrary */

#ifndef _Included_com_desaco_desacocarrybeauty_gpu_image_GPUImageNativeLibrary
#define _Included_com_desaco_desacocarrybeauty_gpu_image_GPUImageNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_desacocarrybeauty_gpu_image_GPUImageNativeLibrary
 * Method:    YUVtoRBGA
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_com_desaco_desacocarrybeauty_gpu_1image_GPUImageNativeLibrary_YUVtoRBGA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     com_desaco_desacocarrybeauty_gpu_image_GPUImageNativeLibrary
 * Method:    YUVtoARBG
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_com_desaco_desacocarrybeauty_gpu_1image_GPUImageNativeLibrary_YUVtoARBG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
